[package]
name = "xtask"
version = "0.1.0"
publish = false
license = "MIT"
edition = "2021"

[[bin]]
name = "xtask"
path = "src/main.rs"

[dependencies]
clap = { workspace = true }
color-eyre = { workspace = true }
duct = "1.1.0"
glob = "0.3"
serde = { workspace = true }
serde_json = { workspace = true }
