use color_eyre::eyre::{eyre, Result};
use std::env;
use std::fs;
use std::path::{Path, PathBuf};

/// Available git hooks.
const HOOKS: &[&str] = &["pre-commit"];

/// Hook script content — delegates to `cargo xtask lint --staged-only`.
const PRE_COMMIT_SCRIPT: &str = "\
#!/bin/sh
# Generated by: cargo xtask lint --install-hooks
exec cargo xtask lint --staged-only
";

fn get_project_root() -> Result<PathBuf> {
    Ok(env::current_dir()?)
}

fn check_git_repo(root: &Path) -> Result<()> {
    if !root.join(".git").exists() {
        return Err(eyre!("Not a git repository. Run from the workspace root."));
    }
    Ok(())
}

/// Install the pre-commit hook.
pub fn install_hooks() -> Result<()> {
    let root = get_project_root()?;
    check_git_repo(&root)?;

    let git_hooks_dir = root.join(".git").join("hooks");
    fs::create_dir_all(&git_hooks_dir)?;

    for hook in HOOKS {
        let hook_path = git_hooks_dir.join(hook);

        // Backup existing non-generated hook.
        if hook_path.exists() && !hook_path.is_symlink() {
            let ts = chrono::Local::now().format("%Y%m%d_%H%M%S");
            let backup = hook_path.with_extension(format!("backup.{ts}"));
            fs::rename(&hook_path, &backup)?;
            println!("Backed up existing {hook} → {}", backup.display());
        }

        fs::write(&hook_path, PRE_COMMIT_SCRIPT)?;

        #[cfg(unix)]
        {
            use std::os::unix::fs::PermissionsExt;
            fs::set_permissions(&hook_path, fs::Permissions::from_mode(0o755))?;
        }

        println!("Installed {hook} hook");
    }
    Ok(())
}

/// Uninstall the pre-commit hook.
pub fn uninstall_hooks() -> Result<()> {
    let root = get_project_root()?;
    check_git_repo(&root)?;

    let git_hooks_dir = root.join(".git").join("hooks");

    for hook in HOOKS {
        let hook_path = git_hooks_dir.join(hook);
        if hook_path.exists() {
            fs::remove_file(&hook_path)?;
            println!("Removed {hook} hook");
        } else {
            println!("No {hook} hook found");
        }
    }
    Ok(())
}

/// Show hook installation status.
pub fn show_status() -> Result<()> {
    let root = get_project_root()?;
    check_git_repo(&root)?;

    let git_hooks_dir = root.join(".git").join("hooks");

    for hook in HOOKS {
        let hook_path = git_hooks_dir.join(hook);
        let status = if hook_path.exists() {
            "installed"
        } else {
            "not installed"
        };
        println!("{hook}: {status}");
    }
    Ok(())
}
